import re, os
import argparse

####### Process options
parser = argparse.ArgumentParser(description='Parse log records.')
parser.add_argument('input', type=str, help= 'log file generated by wpi-*.py etc.')
parser.add_argument('output', type=str, help= 'output file')
args = parser.parse_args()
input_file = args.input
dump_file = args.output

f = open(dump_file, 'wb')
f.write('accuracy recall precision fscore\n')

block_signs = "#########"

def process_db(datablock):
	accuracy = None
	recall = None
	precision = None
	fscore = None
	for line in datablock:
		acc_re = re.compile(r'^Accuracy: ?(\d+\.?\d+)')
		acc_match = acc_re.match(line)
		if acc_match:
			accuracy = acc_match.group(1)
			continue

		pre_re = re.compile(r'^Precision: ?(\d+\.?\d+)')
		pre_match = pre_re.match(line)
		if pre_match:
			precision = pre_match.group(1)
			continue

		recall_re = re.compile(r'^Recall: ?(\d+\.?\d+)')
		recall_match = recall_re.match(line)
		if recall_match:
			recall = recall_match.group(1)
			continue

		fscore_re = re.compile(r'^F-Score: ?(\d+\.?\d+)')
		fscore_match = fscore_re.match(line)
		if fscore_match:
			fscore = fscore_match.group(1)
			continue

	if accuracy == None: accuracy = -1
	if recall == None: recall = -1
	if precision == None: precision = -1
	if fscore == None: fscore = -1
	dump_line = '{0} {1} {2} {3}'.format(accuracy, recall, precision, fscore)
	print dump_line
	return dump_line

###### process all lines
datablock = []
all_lines = open(input_file, 'rb').readlines()
for line in all_lines:
	if line[0:len(block_signs)] != block_signs:
		if all_lines.index(line) != len(all_lines)-1:
			datablock.append(line)
		else:
			datablock.append(line)
			wline = process_db(datablock)
			f.write(wline+'\n')
			# Reset data block container
			datablock = []
	else:
		if datablock != []:
			wline = process_db(datablock)
			f.write(wline+'\n')
			datablock = []
f.close()
